# Generated by Django 5.1 on 2024-09-14 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='active_property',
            field=models.ManyToManyField(blank=True, default=None, related_name='agent_actives', to='property.property'),
        ),
        migrations.AddField(
            model_name='agent',
            name='inquiry_property',
            field=models.ManyToManyField(blank=True, default=None, related_name='agent_inquiries', to='property.property'),
        ),
        migrations.AddField(
            model_name='agent',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='client',
            name='favourite_property',
            field=models.ManyToManyField(blank=True, default=None, related_name='client_favourites', to='property.property'),
        ),
        migrations.AddField(
            model_name='client',
            name='sell_property',
            field=models.ManyToManyField(blank=True, default=None, related_name='client_selling', to='property.property'),
        ),
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
